---
require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  Exclude:
    - bin/*

Gemspec/RequireMFA:
  Enabled: false

#########
# STYLE #
#########

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  AllowedPatterns: ['expect']

##########
# LAYOUT #
##########

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/LineLength:
  Max: 145

#########
# RSPEC #
#########

RSpec/NoExpectationExample:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for
